export const API_ROUTES = {
  AUTH: {
    LOGIN:             '/login',
    REGISTER:          '/crear',
    ME:                '/auth/me',
    REFRESH:           '/auth/refresh',
    CAMBIAR_PASSWORD:  '/usuarios/mi-password',
    ACTUALIZAR_PERFIL: '/usuarios/mi-perfil',
    MI_ACTIVIDAD:      '/usuarios/mi-actividad',
  },
  EMPRESA: {
    GET:         '/empresa',
    UPDATE:      '/empresa',
    LOGO_BASE64: '/empresa/logo-base64',
    LOGO:        '/empresa/logo',
  },
  INSTALACIONES: {
    LIST: '/instalaciones',
    DETAIL: (id) => `/instalaciones/${id}`,
    BODEGAS: (id) => `/instalaciones/bodegas/${id}`,
  },
  BODEGAS: {
    LIST: '/bodegas',
    DETAIL: (id) => `/bodegas/${id}`,
    INVENTARIO: (id, qs = '') => `/bodegas/inventario/${id}${qs}`,
    UPDATE_ITEM: (id) => `/bodegas/item/${id}`,
  },
  ITEMS: {
    GENERAL:        '/item_general',
    DETAIL:         (id) => `/item_general/${id}`,
    PRECIO_MANUAL:  (id) => `/item_general/${id}/precio-manual`,
    BUSCAR:         (q, tipos) => `/item_general/buscar?q=${encodeURIComponent(q)}${tipos?.length ? `&tipos=${tipos.join(',')}` : ''}`,
    LEGACY_ALL:            '/items',
    MATERIAS_DISPONIBLES:  '/items/materias_disponibles',
  },
  // Rutas de Cartera y Pagos
  CARTERA: {
    RESUMEN: '/cartera/resumen',
    AGING: '/cartera/aging',
    ESTADO_CUENTA: (clienteId) => `/cartera/estado_cuenta/${clienteId}`,
  },
  PAGOS: {
    LIST: '/pagos_cliente',
    CREATE: '/pagos_cliente',
    DELETE: (id) => `/pagos_cliente/${id}`,
    BY_CLIENT: (clienteId) => `/pagos_cliente?cliente_id=${clienteId}`,
  },
  GESTIONES: {
    LIST: '/gestiones_cobro',
    BY_FACTURA: (facturaId) => `/gestiones_cobro?factura_id=${facturaId}`,
    BY_CLIENTE: (clienteId) => `/gestiones_cobro?cliente_id=${clienteId}`,
    CREATE: '/gestiones_cobro',
    DELETE: (id) => `/gestiones_cobro/${id}`,
  },
  NOTAS_CREDITO: {
    LIST: '/notas_credito',
    BY_FACTURA: (facturaId) => `/notas_credito?factura_id=${facturaId}`,
    BY_CLIENTE: (clienteId) => `/notas_credito?cliente_id=${clienteId}`,
    CREATE: '/notas_credito',
    ANULAR: (id) => `/notas_credito/${id}/anular`,
  },
  CATALOGO: {
    LIST:        '/catalogo',
    DETAIL:      (id) => `/catalogo/${id}`,
    PROVEEDORES: (id) => `/catalogo/${id}/proveedores`,
  },
  UNIDADES: {
    LIST:   '/unidades',
    CREATE: '/unidades',
    UPDATE: (id) => `/unidades/${id}`,
    DELETE: (id) => `/unidades/${id}`,
  },
  INVENTARIO: {
    GLOBAL:         '/inventario/global',
    TRASPASO:       '/inventario/traspaso',
    AJUSTE_MANUAL:  '/inventario/ajuste-manual',
    REMOVE_BODEGA:  (itemId, bodegaId) => `/inventario/${itemId}/bodega/${bodegaId}`,
  },
  CAPAS: {
    POR_ITEM:       (itemId) => `/inventario/${itemId}/capas`,
    BODEGAS:        '/inventario/capas/bodegas',
    POR_PREPARACION:(prepId) => `/inventario/capas/preparacion/${prepId}`,
  },
  FORMULACIONES: {
    LIST:                  '/formulaciones',
    CREATE:                '/formulaciones',
    DETAIL:                (id) => `/formulaciones/${id}`,
    UPDATE:                (id) => `/formulaciones/${id}`,
    COSTOS:                (id) => `/formulaciones/costos/${id}`,
    RECALCULAR:            (id, volumen) => `/formulaciones/recalcular_costos/${id}/${volumen}`,
    PROVEEDORES:           (id) => `/formulaciones/${id}/proveedores`,
    COSTOS_PROVEEDOR:      (id, proveedorId) => `/formulaciones/costos/${id}/proveedor/${proveedorId}`,
    OPCIONES_INGREDIENTES: (itemId) => `/formulaciones/${itemId}/opciones-ingredientes`,
    BY_ITEM:               (itemId) => `/formulacion_item/${itemId}`,
    CLONAR:                '/formulaciones/clonar',
    VERSIONES:             (id) => `/formulaciones/${id}/versiones`,
    VERSION_DETALLE:       (versionId) => `/formulaciones/versiones/${versionId}`,
    VERSION_RESTAURAR:     (versionId) => `/formulaciones/versiones/${versionId}/restaurar`,
  },
  PROVEEDORES: '/proveedores',
  ITEM_PROVEEDORES: {
    LIST:     '/item_proveedores',
    CREATE:   '/item_proveedores',
    UPDATE:   (id) => `/item_proveedores/${id}`,
    DELETE:   (id) => `/item_proveedores/${id}`,
    VINCULAR: (id) => `/item_proveedores/${id}/vincular`,
  },
  CLIENTES: '/clientes',
  CATEGORIAS: {
    LIST:   '/categorias',
    CREATE: '/categorias',
    UPDATE: (id) => `/categorias/${id}`,
    DELETE: (id) => `/categorias/${id}`,
  },
  COTIZACIONES: {
    LIST:        '/cotizaciones',
    BY_CLIENT:   (clienteId) => `/cotizaciones?cliente_id=${clienteId}`,
    DETAIL:      (id) => `/cotizaciones/${id}`,
    DETALLE:     (id) => `/cotizaciones/${id}/detalle`,
    CREATE:      '/cotizaciones',
    UPDATE:      (id) => `/cotizaciones/${id}`,
    DELETE:      (id) => `/cotizaciones/${id}`,
    ESTADO:      (id) => `/cotizaciones/${id}/estado`,
    CONVERTIR:   (id) => `/cotizaciones/${id}/convertir`,
  },
  FACTURAS: {
    LIST:        '/facturas',
    DETAIL:      (id) => `/facturas/${id}`,
    DETALLE:     (id) => `/facturas/${id}/detalle`,
    ABONOS:      (id) => `/facturas/${id}/abonos`,
    REMISION:    (id) => `/facturas/${id}/remision`,
    CREATE:      '/facturas',
    UPDATE:      (id) => `/facturas/${id}`,
    DELETE:      (id) => `/facturas/${id}`,
    ESTADO:      (id) => `/facturas/${id}/estado`,
  },
  REMISIONES: {
    LIST:        '/remisiones',
    BY_FACTURA:  (facturaId) => `/remisiones?factura_id=${facturaId}`,
    BY_CLIENT:   (clienteId) => `/remisiones?cliente_id=${clienteId}`,
    DETAIL:      (id) => `/remisiones/${id}`,
    DETALLE:     (id) => `/remisiones/${id}/detalle`,
    CREATE:      '/remisiones',
    UPDATE:      (id) => `/remisiones/${id}`,
    DELETE:      (id) => `/remisiones/${id}`,
    ESTADO:      (id) => `/remisiones/${id}/estado`,
    CONVERTIR:   (id) => `/remisiones/${id}/convertir`,
  },
  PREPARACIONES: {
    LIST:                   '/preparaciones',
    LIST_QS:                (qs = '') => `/preparaciones${qs}`,
    CREATE:                 '/preparaciones',
    DETAIL:                 (id) => `/preparaciones/${id}`,
    BY_ITEM:                (itemId) => `/preparaciones/item/${itemId}`,
    COSTOS_RESUMEN:         (qs = '') => `/preparaciones/costos_resumen${qs}`,
    VERIFICAR_DISPONIBILIDAD: (itemId, cantidad, unidadId) =>
      `/preparaciones/verificar-disponibilidad?item_general_id=${itemId}&cantidad=${cantidad}&unidad_id=${unidadId}`,
  },
  ROLES: {
    PERMISOS:          '/roles/permisos',
    PERMISOS_ROL:      (rol) => `/roles/permisos/${rol}`,
    UPDATE_PERMISOS:   (rol) => `/roles/${rol}/permisos`,
    USUARIOS:          '/roles/usuarios',
    CAMBIAR_ROL:       (id)  => `/roles/usuarios/${id}/rol`,
  },
  REQUISICIONES: {
    LIST:           '/requisiciones',
    LIST_BY_ESTADO: (estado) => `/requisiciones?estado=${encodeURIComponent(estado)}`,
    CREATE:         '/requisiciones',
    SUGERIR_MRP:    '/requisiciones/sugerir-mrp',
    POR_PREPARACION:(prepId) => `/requisiciones/preparacion/${prepId}`,
    ESTADO:         (id)     => `/requisiciones/${id}/estado`,
    CONVERTIR_OC:   '/requisiciones/convertir-oc',
  },
  DASHBOARD: '/dashboard',
  NOTIFICACIONES: {
    LIST:        '/notificaciones',
    UNREAD_COUNT:'/notificaciones/no-leidas',
    LEER:        (id) => `/notificaciones/${id}/leer`,
    LEER_TODAS:  '/notificaciones/leer-todas',
  },
  TRAZABILIDAD: {
    POR_PREPARACION: (id)   => `/trazabilidad/preparacion/${id}`,
    POR_LOTE:        (lote) => `/trazabilidad/lote/${encodeURIComponent(lote)}`,
    LOTES_SEARCH:    (q)    => `/trazabilidad/lotes${q ? `?q=${encodeURIComponent(q)}` : ''}`,
  },
  SEARCH: (q, limit = 5) => `/search?q=${encodeURIComponent(q)}&limit=${limit}`,
  SINCRONIZACION: {
    STATS:      '/sincronizacion/stats',
    MAESTRO:    '/sincronizacion/maestro',
    PENDIENTES: '/sincronizacion/pendientes',
    DUPLICADOS: '/sincronizacion/duplicados',
    HUERFANOS:  '/sincronizacion/huerfanos',
    MERGE:      '/sincronizacion/merge',
    USO_FORMULAS:       (id, toId) => `/sincronizacion/uso-formulas/${id}${toId ? `?to=${toId}` : ''}`,
    REEMPLAZAR_FORMULA: '/sincronizacion/reemplazar-formula',
    REEMPLAZOS:         '/sincronizacion/reemplazos',
    REVERTIR_REEMPLAZO: (id) => `/sincronizacion/reemplazos/${id}/revertir`,
    IA: {
      CLASIFICAR: '/sincronizacion/ia/clasificar',
      CLUSTERS:   '/sincronizacion/ia/clusters',
      CLUSTER:    (id) => `/sincronizacion/ia/clusters/${id}`,
      FUSIONAR:   (id) => `/sincronizacion/ia/clusters/${id}/fusionar`,
      DESCARTAR:  (id) => `/sincronizacion/ia/clusters/${id}/descartar`,
      MOVER_ITEM: (id) => `/sincronizacion/ia/cluster-items/${id}`,
      VERIFICAR:  (keepId) => `/sincronizacion/ia/verificar/${keepId}`,
      REVERTIR:   (id) => `/sincronizacion/ia/auditoria/${id}/revertir`,
    },
  },
  ORDENES_COMPRA: {
    LIST:               '/ordenes_compra',
    DETAIL:             (id) => `/ordenes_compra/${id}/detalle`,
    CREATE:             '/ordenes_compra',
    UPDATE:             (id) => `/ordenes_compra/${id}`,
    DELETE:             (id) => `/ordenes_compra/${id}`,
    UPDATE_ESTADO:      (id) => `/ordenes_compra/${id}/estado`,
    RECIBIR_LINEA:      (id, idDetalle) => `/ordenes_compra/${id}/recibir/${idDetalle}`,
    RECIBIR_PRORRATEADO:(id) => `/ordenes_compra/${id}/recibir-prorrateado`,
    LOTE_SUGERIDO:      (id) => `/ordenes_compra/${id}/lote-sugerido`,
  },
  COSTOS_PRODUCCION: {
    LIST:     '/costos-produccion',
    SHOW:     (id) => `/costos-produccion/${id}`,
    HISTORIA: (id) => `/costos-produccion/${id}/historia`,
  },
  SALUD_SISTEMA: '/salud-sistema',
  AUDITORIA: {
    LOGIN_ATTEMPTS: (qs = '') => `/auditoria/login-attempts${qs}`,
    MOVIMIENTOS:    (qs = '') => `/auditoria/movimientos${qs}`,
  },
  CONFIGURACION: {
    ALL:              '/configuracion',
    GRUPO:            (grupo) => `/configuracion/grupo/${grupo}`,
    UPDATE:           (clave) => `/configuracion/${clave}`,
    BULK_UPDATE:      '/configuracion/bulk',
    TIPOS_MOVIMIENTO: '/configuracion/tipos-movimiento',
  },
  NUMERACION: {
    LIST:   '/numeracion',
    CREATE: '/numeracion',
    UPDATE: (id) => `/numeracion/${id}`,
  },
  MOVIMIENTOS: {
    LIST:         (qs = '') => `/movimientos${qs}`,
    RESPONSABLES: '/movimientos/responsables',
  },
  COSTOS_ITEM: {
    UPDATE: (id) => `/costos_item/${id}`,
  },
  COMPARADOR: {
    POR_ITEM:      '/comparador/por_item',
    POR_PROVEEDOR: (proveedorId) => `/comparador/por_proveedor/${proveedorId}`,
    HISTORIAL:     (itemProveedorId) => `/comparador/historial/${itemProveedorId}`,
  },
  COSTOS_INDIRECTOS: {
    LIST:    '/costos_indirectos',
    RESUMEN: '/costos_indirectos/resumen',
  },
};